### ISSUE TITLE
sb

### ISSUE THREAD

**Issue by Yutti7** [Omooo/Omooo#1]

**Comment by Omooo** [comment]
懂你意思～

**Comment by Yutti7** [comment]
……

**Comment by Omooo** [comment]
没啥要骂的话，我一会就 close 了哈～

**Comment by Yutti7** [comment]
你到底是干嘛的..

**Comment by Omooo** [comment]
这句话不应该是我问你吗哥哥？

**Comment by Yutti7** [comment]
你这个项目，啥都没有，你不是说懂我意思

**Comment by Omooo** [comment]
哦哦，看来你是没有理解这个项目是干啥用的呀，这个项目是配置个人主页的，所以只有一个 README.md 文件。
详细可见文档说明：https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme

**Comment by Yutti7** [comment]
哦哦，我以为你创了个空项目
